
#include <Rinternals.h>
#include <R_ext/Rdynload.h>

SEXP grib_c_info(SEXP path, SEXP maxLength);

static const R_CallMethodDef CallEntries[] = {
  {"grib_c_info", (DL_FUNC) &grib_c_info, 2},
  {NULL, NULL, 0}
};
/* end generated by data-raw/make-callentries.R */

void R_init_grib(DllInfo *dll) {
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
}
